# pylint: disable=C0111
# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('..'))
import os
import sys
sys.path.insert(0, os.path.abspath('..'))


# -- Project information -----------------------------------------------------
project = "cfelpyutils"  # pylint: disable=C0103
copyright = (  # pylint: disable=C0103, W0622
    """
    Copyright © 2018 Deutsches Elektronen-Synchrotron DESY,'
    'a research centre of the Helmholtz Association.'
    """
)
author = "OnDA Team"  # pylint: disable=C0103

# The short X.Y version
version = "0.9"  # pylint: disable=C0103
# The full version, including alpha/beta/rc tags
release = "0.9"  # pylint: disable=C0103


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [  # pylint: disable=C0103
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.todo',
    'sphinx.ext.napoleon',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']  # pylint: disable=C0103

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ".rst"  # pylint: disable=C0103

# The master toctree document.
master_doc = "index"  # pylint: disable=C0103

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"  # pylint: disable=C0103

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = [  # pylint: disable=C0103
    '_build',
    'Thumbs.db',
    '.DS_Store'
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'  # pylint: disable=C0103

# -- Extension configuration -------------------------------------------------
add_module_names = False  # pylint: disable=C0103
autodoc_member_order = 'bysource'  # pylint: disable=C0103
autoclass_content = 'init'  # pylint: disable=C0103
